stages:
    - validate
    - plan
    - apply
    - destroy
    - deploy-app

image:
    name: hashicorp/terraform:latest
    entrypoint:
        - '/usr/bin/env'
        - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
    env_name: dev

before_script:
    - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - rm -rf .terraform
    - terraform --version
    - terraform init

Terrafrom_validate:
    stage: validate
    script:
        - terraform validate

Terraform_plan:
    stage: plan
    script: 
        - terraform plan -var-file="env-config/${env_name}.tfvars" -out=tfplan
    artifacts:
        paths:
            - tfplan
    environment:
        name: $env_name

Terraform_apply:
    stage: apply
    script:
        - terraform apply -auto-approve tfplan
    when: manual
    dependencies:
        - Terraform_plan
    environment:
        name: $env_name

Terrafrom_destroy:
    stage: destroy
    script:
        - terraform destroy -var-file="env-config/${env_name}.tfvars" -auto-approve
    when: manual
    dependencies:
        - Terraform_apply
    environment:
        name: $env_name
        action: stop
